# Generated by Django 3.0.6 on 2020-05-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='body',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='date',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='a little about me'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='description',
            field=models.TextField(default='a little this food'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='instructions',
            field=models.TextField(default='begin with...'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='time_required',
            field=models.CharField(default='10 mins', max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='your name', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='title',
            field=models.CharField(default='name of food', max_length=30),
        ),
    ]
