# Generated by Django 3.0.6 on 2020-06-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200630_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='favorite',
        ),
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='recipes.RecipeItem'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Author'),
        ),
    ]
